FROM python:3.11
WORKDIR /code
COPY ./pyproject.toml /code/pyproject.toml
COPY ./alembic.ini /code/alembic.ini
RUN ls
RUN pip3 install -e .
RUN pip3 install .[dev]
COPY . /code/

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "80"]